-- =====================================================
-- PROYECTO: SISTEMA DE GESTIÓN DE BIBLIOTECA
-- ARCHIVO: 01_creacion_tablas.sql
-- =====================================================


-- =====================================================
-- 1. TABLA CATEGORIA
-- =====================================================

CREATE TABLE categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(250),

    CONSTRAINT pk_categoria
        PRIMARY KEY (id_categoria),

    CONSTRAINT uk_categoria_nombre
        UNIQUE (nombre)
);


-- =====================================================
-- 2. TABLA USUARIO
-- =====================================================

CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    fecha_registro DATE DEFAULT SYSDATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',

    CONSTRAINT pk_usuario
        PRIMARY KEY (id_usuario),

    CONSTRAINT uk_usuario_email
        UNIQUE (email),

    CONSTRAINT ck_usuario_estado
        CHECK (estado IN ('ACTIVO', 'BLOQUEADO'))
);


-- =====================================================
-- 3. TABLA LIBRO
-- =====================================================

CREATE TABLE libro (
    id_libro NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR2(200) NOT NULL,
    autor VARCHAR2(150) NOT NULL,
    id_categoria NUMBER NOT NULL,
    anio_publicacion NUMBER(4),
    stock NUMBER DEFAULT 1,

    CONSTRAINT pk_libro
        PRIMARY KEY (id_libro),

    CONSTRAINT fk_libro_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria),

    CONSTRAINT ck_libro_stock
        CHECK (stock >= 0)
);


-- =====================================================
-- 4. TABLA PRESTAMO
-- =====================================================

CREATE TABLE prestamo (
    id_prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER NOT NULL,
    id_libro NUMBER NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE,
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',

    CONSTRAINT pk_prestamo
        PRIMARY KEY (id_prestamo),

    CONSTRAINT fk_prestamo_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario),

    CONSTRAINT fk_prestamo_libro
        FOREIGN KEY (id_libro)
        REFERENCES libro(id_libro),

    CONSTRAINT ck_prestamo_estado
        CHECK (estado IN ('ACTIVO', 'DEVUELTO'))
);


-- =====================================================
-- 5. TABLA DEVOLUCION
-- =====================================================

CREATE TABLE devolucion (
    id_devolucion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_prestamo NUMBER NOT NULL,
    fecha_devolucion DATE DEFAULT SYSDATE,
    dias_atraso NUMBER DEFAULT 0,
    multa NUMBER(10,2) DEFAULT 0,

    CONSTRAINT pk_devolucion
        PRIMARY KEY (id_devolucion),

    CONSTRAINT fk_devolucion_prestamo
        FOREIGN KEY (id_prestamo)
        REFERENCES prestamo(id_prestamo),

    CONSTRAINT ck_devolucion_dias
        CHECK (dias_atraso >= 0),

    CONSTRAINT ck_devolucion_multa
        CHECK (multa >= 0)
);


